---
title: Enhancing weather-based disease forecast with remote sensing: An openenly available cercospora leaf spot simulation model to aid disease detection in sugarbeet
author: 
  - Dr. Rene Heim, Universität Bonn and Institut für Zuckerrübenforschung
  - Dr. Paul Melloy, The University of Queensland  
  - Nathan Okole, University of Gottingen  
  - Facundo Ispizua, Institut für Zuckerrübenforschung
date: "`r Sys.Date()`"
output: html_document
bibliography: inst/cercospora.bib
---

*Cercospora beticola* is a common limiting factor in the growth and production of
sugarbeet (*Beta vulgaris*). 
Managing the impact of the pathogen on plant productivity, biomass accumulation 
and subsequently sugar yields requires fungicide applications to be applied at 
first incidence in the field.
Predicting the initial incidence of cercospora leaf spot in the field has been 
the focus of plant disease models since 1972 (@rossi_cercopri_1991).  

Appearance of the disease is seasonal between the middle of June to the middle of 
August in southern Europe (@rossi_cercopri_1991) and is most likely to occur in 
early July.
This pattern might be explained by the temperature and moisture requirements for 
production of conidiophores from pseudostromata surviving in the soil.
This is similar to requirements for *Didimella pinoides* (@salam_g1_2011) or 
*Leptosphaeria maculans* () pseudothecial maturity and ascospore production
(@salam_blackleg_2003, @salam_g1_2011).


Genotype specific effects of partitioning to above ground. 

Racca (@racca_cercbet_2007) CERCBET 3 reports excellent estimation for the onset 
of Cercospora and action thresholds for a fungicidal intervention. Yet the report
stops short of reporting the coefficients or formulas for reproducing the work.  

The model described by Racca et. al (2007), uses daily infection values to determine
when an epidemic has commenced. 
An epidemic was described to commence when 50% of plants show disease symptoms.
This metric translates to 0.01% of leaf area infected.  
Canopy closure occurs when 90% of plants leaves in adjacent rows are touching.
Canopy closure could be calculated by LAI and is the day when the model begins


## Canopy closure  

Canopy closure is used as the start of models because cercospora spreads mostly by
splash dispersal. 
This means that infection mostly spreads between plants when the canopy is overlapping.
Subsequently spread between rows is much more unlikely , compared to within rows.
